version: "3"
services:

  dashboard:
    build:
      context: ./dashboard
    network_mode: "host"
    volumes:
      - ./dashboard/conf:/www/ppro/dashboard/conf
      - ./dashboard/src:/www/ppro/dashboard/src
      - ./dashboard/scripts:/www/ppro/dashboard/scripts
    entrypoint: /www/ppro/dashboard/scripts/entrypoint.sh
    command: python3 /www/ppro/dashboard/src/server.py --conf=/www/ppro/dashboard/conf/server.conf

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - ./components/prometheus_server/prometheus.yml:/etc/prometheus/prometheus.yml

  monitored_app:
    build:
      context: ./components/monitored_app
    network_mode: "host"
    volumes:
      - ./components/monitored_app/conf:/www/ppro/monitored_app/conf
      - ./components/monitored_app/src:/www/ppro/monitored_app/src

