version: "3"
services:

  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - ./prometheus_server/prometheus.yml:/etc/prometheus/prometheus.yml

  monitored_app:
    build:
      context: ./monitored_app
    network_mode: "host"
    volumes:
      - ./monitored_app/conf:/www/ppro/monitored_app/conf
      - ./monitored_app/src:/www/ppro/monitored_app/src

